USE [master]
GO
/****** Object:  Database [techmartDATA]    Script Date: 19/4/2024 10:45:22 p. m. ******/
CREATE DATABASE [techmartDATA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'techmartDATA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\techmartDATA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'techmartDATA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\techmartDATA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [techmartDATA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [techmartDATA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [techmartDATA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [techmartDATA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [techmartDATA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [techmartDATA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [techmartDATA] SET ARITHABORT OFF 
GO
ALTER DATABASE [techmartDATA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [techmartDATA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [techmartDATA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [techmartDATA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [techmartDATA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [techmartDATA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [techmartDATA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [techmartDATA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [techmartDATA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [techmartDATA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [techmartDATA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [techmartDATA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [techmartDATA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [techmartDATA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [techmartDATA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [techmartDATA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [techmartDATA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [techmartDATA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [techmartDATA] SET  MULTI_USER 
GO
ALTER DATABASE [techmartDATA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [techmartDATA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [techmartDATA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [techmartDATA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [techmartDATA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [techmartDATA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [techmartDATA] SET QUERY_STORE = ON
GO
ALTER DATABASE [techmartDATA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [techmartDATA]
GO
/****** Object:  Table [dbo].[productos]    Script Date: 19/4/2024 10:45:23 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[productos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[precio] [decimal](18, 0) NULL,
	[stock] [int] NOT NULL,
	[descripcion] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[proveedores]    Script Date: 19/4/2024 10:45:23 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[proveedores](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[contacto] [varchar](30) NOT NULL,
	[telefono] [varchar](30) NOT NULL,
	[email] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 19/4/2024 10:45:23 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[contraseña] [varchar](30) NOT NULL,
	[cargo] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[usuarios] ON 
GO
INSERT [dbo].[usuarios] ([ID], [nombre], [contraseña], [cargo]) VALUES (1, N'eira', N'pirulin123', N'administrador')
GO
SET IDENTITY_INSERT [dbo].[usuarios] OFF
GO
USE [master]
GO
ALTER DATABASE [techmartDATA] SET  READ_WRITE 
GO
